/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specifies the date and time a client requests to cancel their Constant Contact account and changes the account `billing_status` to `Canceled`. By default, this is the current date and time in ISO format. In the request body, you can optionally specify a future cancellation date (in ISO format) and a reason (`reason_code`) that the client wants to cancel their account.
 * @export
 * @interface AccountCancellation
 */
export interface AccountCancellation {
    /**
     * Specifies the reason that the client is canceling their Constant Contact account as follows:   <ul>     <li><code>1</code>  Cost Too High</li>     <li><code>2</code>  Using A Competitive Service</li>     <li><code>3</code>  Not Doing Email Marketing</li>     <li><code>11</code> Something Missing Or Not Working </li>     <li><code>12</code> Doing It In-House</li>     <li><code>14</code> Poor Results</li>     <li><code>21</code> Too Difficult To Use</li>     <li><code>27</code> Canceled Online by Customer</li>     <li><code>30</code> Dissatisfied With Billing Policies</li>   </ul>
     * @type {number}
     * @memberof AccountCancellation
     */
    'reason_id'?: number;
    /**
     * The client account cancellation date and time in ISO-8601 format.
     * @type {string}
     * @memberof AccountCancellation
     */
    'effective_date'?: string;
}

