/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountPhysicalAddress
 */
export interface AccountPhysicalAddress {
    /**
     * Line 1 of the organization\'s street address.
     * @type {string}
     * @memberof AccountPhysicalAddress
     */
    'address_line1': string;
    /**
     * Line 2 of the organization\'s street address.
     * @type {string}
     * @memberof AccountPhysicalAddress
     */
    'address_line2'?: string;
    /**
     * Line 3 of the organization\'s street address.
     * @type {string}
     * @memberof AccountPhysicalAddress
     */
    'address_line3'?: string;
    /**
     * The city where the organization is located.
     * @type {string}
     * @memberof AccountPhysicalAddress
     */
    'city': string;
    /**
     * The two letter ISO 3166-1 code for the organization\'s state and only used if the <code>country_code</code> is <code>US</code> or <code>CA</code>. If not, exclude this property from the request body.
     * @type {string}
     * @memberof AccountPhysicalAddress
     */
    'state_code'?: string;
    /**
     * Use if the state where the organization is physically located is not in the United States or Canada. If  <code>country_code</code> is  <code>US</code> or <code>CA</code>, exclude this property from the request body.
     * @type {string}
     * @memberof AccountPhysicalAddress
     */
    'state_name'?: string;
    /**
     * The postal code address (ZIP code) of the organization. This property is required if the <code>state_code</code> is <code>US</code> or <code>CA</code>, otherwise exclude this property from the request body.
     * @type {string}
     * @memberof AccountPhysicalAddress
     */
    'postal_code'?: string;
    /**
     * The two letter <a href=\'https://en.wikipedia.org/wiki/ISO_3166-1\' target=\'_blank\'>ISO 3166-1 code</a> for the organization\'s country.
     * @type {string}
     * @memberof AccountPhysicalAddress
     */
    'country_code': string;
}

