/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetAllActivities200ResponseActivitiesInnerLinksSelf } from './get-all-activities200-response-activities-inner-links-self';

/**
 * 
 * @export
 * @interface ActivityStatusLink
 */
export interface ActivityStatusLink {
    /**
     * 
     * @type {GetAllActivities200ResponseActivitiesInnerLinksSelf}
     * @memberof ActivityStatusLink
     */
    'self'?: GetAllActivities200ResponseActivitiesInnerLinksSelf;
}

