/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetAllActivities200ResponseActivitiesInnerLinks } from './get-all-activities200-response-activities-inner-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetAllActivities200ResponseActivitiesInnerStatus } from './get-all-activities200-response-activities-inner-status';

/**
 * Generic bulk activity status response object
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * Unique ID for the activity.
     * @type {string}
     * @memberof Activity
     */
    'activity_id'?: string;
    /**
     * The state of the request: <p><ul> <li>initialized - request has been received</li> <li>processing - request is being processed</li> <li>completed - job completed</li> <li>cancelled - request was cancelled</li> <li>failed - job failed to complete</li> <li>timed_out - the request timed out before completing\"</li> </ul> </p>
     * @type {string}
     * @memberof Activity
     */
    'state'?: string;
    /**
     * Timestamp showing when we began processing the activity request, in ISO-8601 format.
     * @type {string}
     * @memberof Activity
     */
    'started_at'?: string;
    /**
     * Timestamp showing when we completed processing the activity, in ISO-8601 format.
     * @type {string}
     * @memberof Activity
     */
    'completed_at'?: string;
    /**
     * Timestamp showing when we created the activity, in ISO-8601 format.
     * @type {string}
     * @memberof Activity
     */
    'created_at'?: string;
    /**
     * Timestamp showing when we last updated the activity, in ISO-8601 format.
     * @type {string}
     * @memberof Activity
     */
    'updated_at'?: string;
    /**
     * Name of the file used for an add_contacts activity.
     * @type {string}
     * @memberof Activity
     */
    'source_file_name'?: string;
    /**
     * Shows the percent done for an activity that we are still processing.
     * @type {number}
     * @memberof Activity
     */
    'percent_done'?: number;
    /**
     * Array of messages describing the errors that occurred.
     * @type {Array<string>}
     * @memberof Activity
     */
    'activity_errors'?: Array<string>;
    /**
     * 
     * @type {GetAllActivities200ResponseActivitiesInnerStatus}
     * @memberof Activity
     */
    'status'?: GetAllActivities200ResponseActivitiesInnerStatus;
    /**
     * 
     * @type {GetAllActivities200ResponseActivitiesInnerLinks}
     * @memberof Activity
     */
    '_links'?: GetAllActivities200ResponseActivitiesInnerLinks;
}

