/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyLogo
 */
export interface CompanyLogo {
    /**
     * The internal URL used to get the company logo image file hosted locally in your account\'s MyLibrary.
     * @type {string}
     * @memberof CompanyLogo
     */
    'url'?: string;
    /**
     * The external URL used to get the company logo image file that is hosted on an external website.
     * @type {string}
     * @memberof CompanyLogo
     */
    'external_url'?: string;
    /**
     * The internal ID used to identify the image hosted in your account\'s MyLibrary.
     * @type {string}
     * @memberof CompanyLogo
     */
    'internal_id'?: string;
}

