/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetContactById200ResponseCustomFieldsInner } from './get-contact-by-id200-response-custom-fields-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetContactById200ResponseNotesInner } from './get-contact-by-id200-response-notes-inner';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateContactRequestEmailAddress } from './update-contact-request-email-address';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateContactRequestPhoneNumbersInner } from './update-contact-request-phone-numbers-inner';
// May contain unused imports in some cases
// @ts-ignore
import { UpdateContactRequestStreetAddressesInner } from './update-contact-request-street-addresses-inner';

/**
 * 
 * @export
 * @interface ContactPutRequest
 */
export interface ContactPutRequest {
    /**
     * 
     * @type {UpdateContactRequestEmailAddress}
     * @memberof ContactPutRequest
     */
    'email_address'?: UpdateContactRequestEmailAddress;
    /**
     * The contact\'s first name
     * @type {string}
     * @memberof ContactPutRequest
     */
    'first_name'?: string;
    /**
     * The contact\'s last name
     * @type {string}
     * @memberof ContactPutRequest
     */
    'last_name'?: string;
    /**
     * The contact\'s job title
     * @type {string}
     * @memberof ContactPutRequest
     */
    'job_title'?: string;
    /**
     * Name of the company the contact works for.
     * @type {string}
     * @memberof ContactPutRequest
     */
    'company_name'?: string;
    /**
     * Accepts values from 1-12; must be used with <code>birthday_day</code>
     * @type {number}
     * @memberof ContactPutRequest
     */
    'birthday_month'?: number;
    /**
     * Accepts values from 1-31; must be used with <code>birthday_month</code>
     * @type {number}
     * @memberof ContactPutRequest
     */
    'birthday_day'?: number;
    /**
     * The anniversary date; Accepted formats are MM/DD/YYYY, M/D/YYYY, YYYY/MM/DD, YYYY/M/D, YYYY-MM-DD, YYYY-M-D, MM-DD-YYYY, M-D-YYYY
     * @type {string}
     * @memberof ContactPutRequest
     */
    'anniversary'?: string;
    /**
     * Identifies who last updated the contact; valid values are <code>Contact</code> or <code>Account</code>.
     * @type {string}
     * @memberof ContactPutRequest
     */
    'update_source': string;
    /**
     * Array of up to 25 <code>custom_field</code> subresources.
     * @type {Array<GetContactById200ResponseCustomFieldsInner>}
     * @memberof ContactPutRequest
     */
    'custom_fields'?: Array<GetContactById200ResponseCustomFieldsInner>;
    /**
     * Array of up to 3 <code>phone_numbers</code> subresources.
     * @type {Array<UpdateContactRequestPhoneNumbersInner>}
     * @memberof ContactPutRequest
     */
    'phone_numbers'?: Array<UpdateContactRequestPhoneNumbersInner>;
    /**
     * Array of up to 3 <code>street_addresses</code> subresources.
     * @type {Array<UpdateContactRequestStreetAddressesInner>}
     * @memberof ContactPutRequest
     */
    'street_addresses'?: Array<UpdateContactRequestStreetAddressesInner>;
    /**
     * Array of up to 50 <code>list_ids</code> to which the contact is subscribed.
     * @type {Array<string>}
     * @memberof ContactPutRequest
     */
    'list_memberships'?: Array<string>;
    /**
     * Array of tags (<code>tag_id</code>) assigned to the contact, up to a maximum of 50.
     * @type {Array<string>}
     * @memberof ContactPutRequest
     */
    'taggings'?: Array<string>;
    /**
     * An array of notes about the contact listed by most recent note first.
     * @type {Array<GetContactById200ResponseNotesInner>}
     * @memberof ContactPutRequest
     */
    'notes'?: Array<GetContactById200ResponseNotesInner>;
}

