/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetAllActivities200ResponseLinks } from './get-all-activities200-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetList200Response } from './get-list200-response';

/**
 * 
 * @export
 * @interface ContactListArray
 */
export interface ContactListArray {
    /**
     * 
     * @type {Array<GetList200Response>}
     * @memberof ContactListArray
     */
    'lists'?: Array<GetList200Response>;
    /**
     * The total number of contact lists.
     * @type {number}
     * @memberof ContactListArray
     */
    'lists_count'?: number;
    /**
     * 
     * @type {GetAllActivities200ResponseLinks}
     * @memberof ContactListArray
     */
    '_links'?: GetAllActivities200ResponseLinks;
}

