/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetContactTrackingCountReport200ResponseCampaignActivitiesInner } from './get-contact-tracking-count-report200-response-campaign-activities-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetContactTrackingCountReport200ResponseLinks } from './get-contact-tracking-count-report200-response-links';

/**
 * 
 * @export
 * @interface ContactCampaignActivitiesSummary
 */
export interface ContactCampaignActivitiesSummary {
    /**
     * Unique id of the contact that will have their activity summarized.
     * @type {string}
     * @memberof ContactCampaignActivitiesSummary
     */
    'contact_id': string;
    /**
     * A summary of all the actions for a contact.
     * @type {Array<GetContactTrackingCountReport200ResponseCampaignActivitiesInner>}
     * @memberof ContactCampaignActivitiesSummary
     */
    'campaign_activities': Array<GetContactTrackingCountReport200ResponseCampaignActivitiesInner>;
    /**
     * 
     * @type {GetContactTrackingCountReport200ResponseLinks}
     * @memberof ContactCampaignActivitiesSummary
     */
    '_links'?: GetContactTrackingCountReport200ResponseLinks;
}

