/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateOrUpdateContactRequestStreetAddress
 */
export interface CreateOrUpdateContactRequestStreetAddress {
    /**
     * The type of street address for the contact. Valid values are <code>home</code>, <code>work</code>, or <code>other</code>.
     * @type {string}
     * @memberof CreateOrUpdateContactRequestStreetAddress
     */
    'kind': string;
    /**
     * The number and street of the contact\'s address.
     * @type {string}
     * @memberof CreateOrUpdateContactRequestStreetAddress
     */
    'street'?: string;
    /**
     * The name of the city for the contact\'s address.
     * @type {string}
     * @memberof CreateOrUpdateContactRequestStreetAddress
     */
    'city'?: string;
    /**
     * The name of the state or province for the contact\'s address.
     * @type {string}
     * @memberof CreateOrUpdateContactRequestStreetAddress
     */
    'state'?: string;
    /**
     * The zip or postal code for the contact\'s address.
     * @type {string}
     * @memberof CreateOrUpdateContactRequestStreetAddress
     */
    'postal_code'?: string;
    /**
     * The name of the country for the contact\'s address.
     * @type {string}
     * @memberof CreateOrUpdateContactRequestStreetAddress
     */
    'country'?: string;
}

