/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateTagDeleteActivityRequest
 */
export interface CreateTagDeleteActivityRequest {
    /**
     * The tag IDs (<code>tag_ids</code>) to delete.
     * @type {Array<string>}
     * @memberof CreateTagDeleteActivityRequest
     */
    'tag_ids': Array<string>;
}

