/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The <code>source</code> object specifies which contacts you are adding to your targeted lists using one of four mutually exclusive properties.
 * @export
 * @interface CreateListAddActivityRequestSource
 */
export interface CreateListAddActivityRequestSource {
    /**
     * Specifies which contacts you are adding to lists as an array of up to 50 contact <code>list_id</code> values. This property is mutually exclusive with <code>contact_ids</code>, <code>all_active_contacts</code> (billable), and <code>segment_id</code>.
     * @type {Array<string>}
     * @memberof CreateListAddActivityRequestSource
     */
    'list_ids'?: Array<string>;
    /**
     * Adds all active (billable) contacts to your targeted lists. This property is mutually exclusive with <code>contact_ids</code>, <code>list_ids</code>, and <code>segment_id</code>.
     * @type {boolean}
     * @memberof CreateListAddActivityRequestSource
     */
    'all_active_contacts'?: boolean;
    /**
     * Specifies which contacts (up to 500) you are adding to lists as an array of <code>contact_id</code> values. This property is mutually exclusive with <code>list_ids</code>, <code>all_active_contacts</code> (billable), and <code>segment_id</code>.
     * @type {Array<string>}
     * @memberof CreateListAddActivityRequestSource
     */
    'contact_ids'?: Array<string>;
    /**
     * Adds all contacts assigned with the specified <code>tag_id</code>s to your target lists. This property is mutually exclusive with all other <code>source</code> properties.
     * @type {Array<string>}
     * @memberof CreateListAddActivityRequestSource
     */
    'tag_ids'?: Array<string>;
    /**
     * Adds all contacts that meet the selected  <code>engagement_level </code> to your target lists. This property is mutually exclusive with all other <code>source</code> properties.
     * @type {string}
     * @memberof CreateListAddActivityRequestSource
     */
    'engagement_level'?: string;
    /**
     * Specifies which contacts you are adding to lists as a single <code>segment_id</code> value. This property is mutually exclusive with <code>list_ids</code>, <code>all_active_contacts</code> (billable), and <code>contact_ids</code>.
     * @type {number}
     * @memberof CreateListAddActivityRequestSource
     */
    'segment_id'?: number;
}

