/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateExportActivity201ResponseStatus
 */
export interface CreateExportActivity201ResponseStatus {
    /**
     * The total number of contacts to export.
     * @type {number}
     * @memberof CreateExportActivity201ResponseStatus
     */
    'items_total_count'?: number;
    /**
     * The number of contacts processed for export.
     * @type {number}
     * @memberof CreateExportActivity201ResponseStatus
     */
    'items_completed_count'?: number;
}

