/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The contact\'s email address and related properties.
 * @export
 * @interface CreateContactRequestEmailAddress
 */
export interface CreateContactRequestEmailAddress {
    /**
     * The contact\'s email address.
     * @type {string}
     * @memberof CreateContactRequestEmailAddress
     */
    'address': string;
    /**
     * Identifies the type of permission that the Constant Contact account has been granted to send email to the contact. Types of permission: explicit, implicit, not_set, pending_confirmation, temp_hold, unsubscribed.
     * @type {string}
     * @memberof CreateContactRequestEmailAddress
     */
    'permission_to_send'?: string;
}

