/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateImportJSONActivityRequestImportDataInner } from './create-import-jsonactivity-request-import-data-inner';

/**
 * 
 * @export
 * @interface CreateImportJSONActivityRequest
 */
export interface CreateImportJSONActivityRequest {
    /**
     * An array containing the contacts to import.
     * @type {Array<CreateImportJSONActivityRequestImportDataInner>}
     * @memberof CreateImportJSONActivityRequest
     */
    'import_data': Array<CreateImportJSONActivityRequestImportDataInner>;
    /**
     * Specify which contact lists you are adding all imported contacts to as an array of up to 50 contact <code>list_id</code> string values.
     * @type {Array<string>}
     * @memberof CreateImportJSONActivityRequest
     */
    'list_ids': Array<string>;
    /**
     * Specifies if the contact gave <code>explicit</code> SMS permission or if the SMS permission was not set (<code>not_set</code>). If `explicit, the <code>sms_consent_date</code> must be provided.
     * @type {string}
     * @memberof CreateImportJSONActivityRequest
     */
    'sms_permission_to_send'?: string;
}

