/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateTagRemoveActivity201ResponseLinks } from './create-tag-remove-activity201-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { CreateTagRemoveActivity201ResponseStatus } from './create-tag-remove-activity201-response-status';

/**
 * 
 * @export
 * @interface CreateTagRemoveActivity201Response
 */
export interface CreateTagRemoveActivity201Response {
    /**
     * The system assigned UUID that uniquely identifies an activity.
     * @type {string}
     * @memberof CreateTagRemoveActivity201Response
     */
    'activity_id': string;
    /**
     * The activity processing state.
     * @type {string}
     * @memberof CreateTagRemoveActivity201Response
     */
    'state': string;
    /**
     * Timestamp showing when processing started for the activity, in ISO-8601 format.
     * @type {string}
     * @memberof CreateTagRemoveActivity201Response
     */
    'started_at'?: string;
    /**
     * Timestamp showing when processing completed for the activity, in ISO-8601 format.
     * @type {string}
     * @memberof CreateTagRemoveActivity201Response
     */
    'completed_at'?: string;
    /**
     * Timestamp showing when the activity was first requested, in ISO-8601 format.
     * @type {string}
     * @memberof CreateTagRemoveActivity201Response
     */
    'created_at'?: string;
    /**
     * Timestamp showing when the activity was last updated, in ISO-8601 format.
     * @type {string}
     * @memberof CreateTagRemoveActivity201Response
     */
    'updated_at'?: string;
    /**
     * The processing percent complete for the activity.
     * @type {number}
     * @memberof CreateTagRemoveActivity201Response
     */
    'percent_done'?: number;
    /**
     * An array of error message strings describing the errors that occurred.
     * @type {Array<string>}
     * @memberof CreateTagRemoveActivity201Response
     */
    'activity_errors'?: Array<string>;
    /**
     * 
     * @type {CreateTagRemoveActivity201ResponseStatus}
     * @memberof CreateTagRemoveActivity201Response
     */
    'status'?: CreateTagRemoveActivity201ResponseStatus;
    /**
     * 
     * @type {CreateTagRemoveActivity201ResponseLinks}
     * @memberof CreateTagRemoveActivity201Response
     */
    '_links'?: CreateTagRemoveActivity201ResponseLinks;
}

