/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specifies the contacts to remove from your target list(s) using one of several mutually exclusive properties.
 * @export
 * @interface CreateListRemoveActivityRequestSource
 */
export interface CreateListRemoveActivityRequestSource {
    /**
     * Include up to 50 <code>list_id</code> values to remove all contact list members from your target list(s). This property is mutually exclusive with all other <code>source</code> properties.
     * @type {Array<string>}
     * @memberof CreateListRemoveActivityRequestSource
     */
    'list_ids'?: Array<string>;
    /**
     * Include up to 500 <code>contact_id</code> values to remove the contacts from your target lists. This property is mutually exclusive with all other <code>source</code> properties.
     * @type {Array<string>}
     * @memberof CreateListRemoveActivityRequestSource
     */
    'contact_ids'?: Array<string>;
    /**
     * Removes all active (billable) contacts from your targeted lists. This property is mutually exclusive with all other <code>source</code> properties.
     * @type {boolean}
     * @memberof CreateListRemoveActivityRequestSource
     */
    'all_active_contacts'?: boolean;
    /**
     * Removes all contacts that meet the selected  <code>engagement_level </code> to your target lists. This property is mutually exclusive with all other <code>source</code> properties.
     * @type {string}
     * @memberof CreateListRemoveActivityRequestSource
     */
    'engagement_level'?: string;
    /**
     * Removes all contacts assigned with the specified <code>tag_id</code>s from your target lists. This property is mutually exclusive with all other <code>source</code> properties.
     * @type {Array<string>}
     * @memberof CreateListRemoveActivityRequestSource
     */
    'tag_ids'?: Array<string>;
}

