/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateListDeleteActivity201ResponseLinksSelf } from './create-list-delete-activity201-response-links-self';

/**
 * 
 * @export
 * @interface CreateListDeleteActivity201ResponseLinks
 */
export interface CreateListDeleteActivity201ResponseLinks {
    /**
     * 
     * @type {CreateListDeleteActivity201ResponseLinksSelf}
     * @memberof CreateListDeleteActivity201ResponseLinks
     */
    'self'?: CreateListDeleteActivity201ResponseLinksSelf;
}

