/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateSegment201Response
 */
export interface CreateSegment201Response {
    /**
     * The segment\'s unique descriptive name.
     * @type {string}
     * @memberof CreateSegment201Response
     */
    'name'?: string;
    /**
     * The segment\'s contact selection criteria formatted as single-string escaped JSON.
     * @type {string}
     * @memberof CreateSegment201Response
     */
    'segment_criteria'?: string;
    /**
     * The system generated number that uniquely identifies the segment.
     * @type {number}
     * @memberof CreateSegment201Response
     */
    'segment_id'?: number;
    /**
     * The system generated date and time (ISO-8601) that the segment was created.
     * @type {string}
     * @memberof CreateSegment201Response
     */
    'created_at'?: string;
    /**
     * The system generated date and time (ISO-8601) that the segment\'s <code>name</code> or <code> segment_criteria</code> was last updated.
     * @type {string}
     * @memberof CreateSegment201Response
     */
    'edited_at'?: string;
}

