/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateDeleteActivity201ResponseLinks } from './create-delete-activity201-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { CreateDeleteActivity201ResponseStatus } from './create-delete-activity201-response-status';

/**
 * Activity status for contact_delete activity
 * @export
 * @interface CreateDeleteActivity201Response
 */
export interface CreateDeleteActivity201Response {
    /**
     * Unique ID for the activity.
     * @type {string}
     * @memberof CreateDeleteActivity201Response
     */
    'activity_id'?: string;
    /**
     * The state of the request: <p><ul> <li>initialized - request has been received</li> <li>processing - request is being processed</li> <li>completed - job completed</li> <li>cancelled - request was cancelled</li> <li>failed - job failed to complete</li> <li>timed_out - the request timed out before completing\"</li> </ul> </p>
     * @type {string}
     * @memberof CreateDeleteActivity201Response
     */
    'state'?: string;
    /**
     * Timestamp showing when we began processing the activity request, in ISO-8601 format.
     * @type {string}
     * @memberof CreateDeleteActivity201Response
     */
    'started_at'?: string;
    /**
     * Timestamp showing when we completed processing the activity, in ISO-8601 format.
     * @type {string}
     * @memberof CreateDeleteActivity201Response
     */
    'completed_at'?: string;
    /**
     * Timestamp showing when we created the activity, in ISO-8601 format.
     * @type {string}
     * @memberof CreateDeleteActivity201Response
     */
    'created_at'?: string;
    /**
     * Timestamp showing when we last updated the activity, in ISO-8601 format.
     * @type {string}
     * @memberof CreateDeleteActivity201Response
     */
    'updated_at'?: string;
    /**
     * Shows the percent done for an activity that we are still processing.
     * @type {number}
     * @memberof CreateDeleteActivity201Response
     */
    'percent_done'?: number;
    /**
     * Array of messages describing the errors that occurred.
     * @type {Array<string>}
     * @memberof CreateDeleteActivity201Response
     */
    'activity_errors'?: Array<string>;
    /**
     * 
     * @type {CreateDeleteActivity201ResponseStatus}
     * @memberof CreateDeleteActivity201Response
     */
    'status'?: CreateDeleteActivity201ResponseStatus;
    /**
     * 
     * @type {CreateDeleteActivity201ResponseLinks}
     * @memberof CreateDeleteActivity201Response
     */
    '_links'?: CreateDeleteActivity201ResponseLinks;
}

