/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetEmailCampaignXrefs200ResponseXrefsInner } from './get-email-campaign-xrefs200-response-xrefs-inner';

/**
 * 
 * @export
 * @interface CrossReferenceResponse
 */
export interface CrossReferenceResponse {
    /**
     * An array of objects that contain a <code>v2_email_campaign_id</code> cross-referenced with a V3 <code>campaign_id</code> and a V3 <code>campaign_activity_id</code> value.
     * @type {Array<GetEmailCampaignXrefs200ResponseXrefsInner>}
     * @memberof CrossReferenceResponse
     */
    'xrefs'?: Array<GetEmailCampaignXrefs200ResponseXrefsInner>;
}

