/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerPut
 */
export interface CustomerPut {
    /**
     * The confirmed email address that is associated with the account owner.
     * @type {string}
     * @memberof CustomerPut
     */
    'contact_email'?: string;
    /**
     * The account owner\'s contact phone number (up to 25 characters in length).
     * @type {string}
     * @memberof CustomerPut
     */
    'contact_phone'?: string;
    /**
     * The two-letter <a href=\'https://en.wikipedia.org/wiki/ISO_3166-1\' target=\'_blank\'>ISO 3166-1 code</a> representing the organization\'s country.
     * @type {string}
     * @memberof CustomerPut
     */
    'country_code'?: string;
    /**
     * The read only encoded account ID that uniquely identifies the account.
     * @type {string}
     * @memberof CustomerPut
     */
    'encoded_account_id'?: string;
    /**
     * The account owner\'s first name.
     * @type {string}
     * @memberof CustomerPut
     */
    'first_name'?: string;
    /**
     * The account owner\'s last name.
     * @type {string}
     * @memberof CustomerPut
     */
    'last_name'?: string;
    /**
     * The name of the organization that is associated with this account.
     * @type {string}
     * @memberof CustomerPut
     */
    'organization_name'?: string;
    /**
     * The phone number of the organization that is associated with this account.
     * @type {string}
     * @memberof CustomerPut
     */
    'organization_phone'?: string;
    /**
     * The two letter <a href=\'https://en.wikipedia.org/wiki/ISO_3166-1\' target=\'_blank\'>ISO 3166-1 code</a> used to specify the state to associate with the account. This property is required if the <code>country_code</code> is US (United States).
     * @type {string}
     * @memberof CustomerPut
     */
    'state_code'?: string;
    /**
     * The time zone to use for the account; as defined in the IANA time-zone database (see http://www.iana.org/time-zones).
     * @type {string}
     * @memberof CustomerPut
     */
    'time_zone_id'?: string;
    /**
     * The organization\'s website URL.
     * @type {string}
     * @memberof CustomerPut
     */
    'website'?: string;
}

