/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateListDeleteActivity201ResponseLinks } from './create-list-delete-activity201-response-links';

/**
 * 
 * @export
 * @interface DeleteList202Response
 */
export interface DeleteList202Response {
    /**
     * Unique ID for the delete list batch job.
     * @type {string}
     * @memberof DeleteList202Response
     */
    'activity_id'?: string;
    /**
     * The state of the request:  <p><ul>  <li>initialized - request has been received</li>  <li>processing - request is being processed</li>  <li>completed - job completed</li>  <li>cancelled - request was cancelled</li>  <li>failed - job failed to complete</li>  <li>timed_out - the request timed out before completing\"</li>   </ul> </p>
     * @type {string}
     * @memberof DeleteList202Response
     */
    'state'?: string;
    /**
     * Date and time that the request was received, in ISO-8601 formmat.
     * @type {string}
     * @memberof DeleteList202Response
     */
    'created_at'?: string;
    /**
     * Date and time that the request status was updated, in ISO-8601 format.
     * @type {string}
     * @memberof DeleteList202Response
     */
    'updated_at'?: string;
    /**
     * Job completion percentage
     * @type {number}
     * @memberof DeleteList202Response
     */
    'percent_done'?: number;
    /**
     * Array of messages describing the errors that occurred.
     * @type {Array<string>}
     * @memberof DeleteList202Response
     */
    'activity_errors'?: Array<string>;
    /**
     * 
     * @type {CreateListDeleteActivity201ResponseLinks}
     * @memberof DeleteList202Response
     */
    '_links'?: CreateListDeleteActivity201ResponseLinks;
}

