/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DeleteTag202ResponseActivityErrorsInner } from './delete-tag202-response-activity-errors-inner';
// May contain unused imports in some cases
// @ts-ignore
import { DeleteTag202ResponseLinks } from './delete-tag202-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { DeleteTag202ResponseStatus } from './delete-tag202-response-status';

/**
 * 
 * @export
 * @interface DeleteTag202Response
 */
export interface DeleteTag202Response {
    /**
     * The ID that uniquely identifies the activity.
     * @type {string}
     * @memberof DeleteTag202Response
     */
    'activity_id': string;
    /**
     * The processing state for the activity.
     * @type {string}
     * @memberof DeleteTag202Response
     */
    'state': string;
    /**
     * The system generated date and time that the resource was created, in ISO-8601 format.
     * @type {string}
     * @memberof DeleteTag202Response
     */
    'created_at'?: string;
    /**
     * The system generated date and time that the resource was last updated, in ISO-8601 format.
     * @type {string}
     * @memberof DeleteTag202Response
     */
    'updated_at'?: string;
    /**
     * The percentage complete for the specified activity.
     * @type {number}
     * @memberof DeleteTag202Response
     */
    'percent_done'?: number;
    /**
     * An array of error messages if errors occurred for a specified activity. The system returns an empty array if no errors occur.
     * @type {Array<DeleteTag202ResponseActivityErrorsInner>}
     * @memberof DeleteTag202Response
     */
    'activity_errors'?: Array<DeleteTag202ResponseActivityErrorsInner>;
    /**
     * 
     * @type {DeleteTag202ResponseStatus}
     * @memberof DeleteTag202Response
     */
    'status'?: DeleteTag202ResponseStatus;
    /**
     * 
     * @type {DeleteTag202ResponseLinks}
     * @memberof DeleteTag202Response
     */
    '_links'?: DeleteTag202ResponseLinks;
}

