/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteTag202ResponseStatus
 */
export interface DeleteTag202ResponseStatus {
    /**
     * The total number of tags that this activity will delete.
     * @type {number}
     * @memberof DeleteTag202ResponseStatus
     */
    'items_total_count'?: number;
    /**
     * The number of tags that this activity has currently deleted.
     * @type {number}
     * @memberof DeleteTag202ResponseStatus
     */
    'items_completed_count'?: number;
}

