/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The link returned in the response that you use to retrieve the status for the specified activity.
 * @export
 * @interface DeleteTag202ResponseLinksSelf
 */
export interface DeleteTag202ResponseLinksSelf {
    /**
     * 
     * @type {string}
     * @memberof DeleteTag202ResponseLinksSelf
     */
    'href'?: string;
}

