/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceFlowResponse
 */
export interface DeviceFlowResponse {
    /**
     * Code you can exchange for an access token.
     * @type {string}
     * @memberof DeviceFlowResponse
     */
    'device_code'?: string;
    /**
     * Code assigned to the Constant Contact user granting access to your application.
     * @type {string}
     * @memberof DeviceFlowResponse
     */
    'user_code'?: string;
    /**
     * URL used by the Constant Contact user to grant access to your application.
     * @type {string}
     * @memberof DeviceFlowResponse
     */
    'verification_uri'?: string;
    /**
     * Verification url with the user code already appended.
     * @type {string}
     * @memberof DeviceFlowResponse
     */
    'verification_uri_complete'?: string;
    /**
     * Time in seconds before the device and user codes expire.
     * @type {number}
     * @memberof DeviceFlowResponse
     */
    'expires_in'?: number;
    /**
     * Polling interval used when identifying if the Constant Contact user has granted access to your application.
     * @type {number}
     * @memberof DeviceFlowResponse
     */
    'interval'?: number;
}

