/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetDidNotOpensReport200ResponseTrackingActivitiesInner } from './get-did-not-opens-report200-response-tracking-activities-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetEmailSendsReport200ResponseLinks } from './get-email-sends-report200-response-links';

/**
 * 
 * @export
 * @interface DidNotOpensTrackingActivitiesPage
 */
export interface DidNotOpensTrackingActivitiesPage {
    /**
     * Lists contacts that did not open the specified <code>campaign_activity_id</code>.
     * @type {Array<GetDidNotOpensReport200ResponseTrackingActivitiesInner>}
     * @memberof DidNotOpensTrackingActivitiesPage
     */
    'tracking_activities': Array<GetDidNotOpensReport200ResponseTrackingActivitiesInner>;
    /**
     * 
     * @type {GetEmailSendsReport200ResponseLinks}
     * @memberof DidNotOpensTrackingActivitiesPage
     */
    '_links'?: GetEmailSendsReport200ResponseLinks;
}

