/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateEmailCampaignRequestEmailCampaignActivitiesInner } from './create-email-campaign-request-email-campaign-activities-inner';

/**
 * 
 * @export
 * @interface EmailCampaignComplete
 */
export interface EmailCampaignComplete {
    /**
     * The unique and descriptive name that you specify for the email campaign.
     * @type {string}
     * @memberof EmailCampaignComplete
     */
    'name': string;
    /**
     * The content of the email campaign as an array that contains a single email campaign activity object.
     * @type {Array<CreateEmailCampaignRequestEmailCampaignActivitiesInner>}
     * @memberof EmailCampaignComplete
     */
    'email_campaign_activities': Array<CreateEmailCampaignRequestEmailCampaignActivitiesInner>;
}

