/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetContactById200ResponseCustomFieldsInner } from './get-contact-by-id200-response-custom-fields-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetContactById200ResponseEmailAddress } from './get-contact-by-id200-response-email-address';
// May contain unused imports in some cases
// @ts-ignore
import { GetContactById200ResponseNotesInner } from './get-contact-by-id200-response-notes-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetContactById200ResponsePhoneNumbersInner } from './get-contact-by-id200-response-phone-numbers-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetContactById200ResponseSmsChannel } from './get-contact-by-id200-response-sms-channel';
// May contain unused imports in some cases
// @ts-ignore
import { GetContactById200ResponseStreetAddressesInner } from './get-contact-by-id200-response-street-addresses-inner';

/**
 * Use this endpoint to retrieve (GET), update (PUT), or DELETE an existing contact resource specified using the <code>contact_id</code> path parameter.
 * @export
 * @interface GetContactById200Response
 */
export interface GetContactById200Response {
    /**
     * Unique ID for each contact resource
     * @type {string}
     * @memberof GetContactById200Response
     */
    'contact_id'?: string;
    /**
     * 
     * @type {GetContactById200ResponseEmailAddress}
     * @memberof GetContactById200Response
     */
    'email_address'?: GetContactById200ResponseEmailAddress;
    /**
     * The first name of the contact.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'first_name'?: string;
    /**
     * The last name of the contact.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'last_name'?: string;
    /**
     * The job title of the contact.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'job_title'?: string;
    /**
     * The name of the company where the contact works.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'company_name'?: string;
    /**
     * The month value for the contact\'s birthday. Valid values are from 1 through 12. You must use this property with <code>birthday_month</code>.
     * @type {number}
     * @memberof GetContactById200Response
     */
    'birthday_month'?: number;
    /**
     * The day value for the contact\'s birthday. Valid values are from 1 through 12. You must use this property with <code>birthday_day</code>.
     * @type {number}
     * @memberof GetContactById200Response
     */
    'birthday_day'?: number;
    /**
     * The anniversary date for the contact. For example, this value could be the date when the contact first became a customer of an organization in Constant Contact. Valid date formats are MM/DD/YYYY, M/D/YYYY, YYYY/MM/DD, YYYY/M/D, YYYY-MM-DD, YYYY-M-D,M-D-YYYY, or M-DD-YYYY.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'anniversary'?: string;
    /**
     * Identifies who last updated the contact; valid values are  <code>Contact</code> or <code>Account</code>.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'update_source'?: string;
    /**
     * Describes who added the contact; valid values are <code>Contact</code> or <code>Account</code>. Your integration must accurately identify <code>create_source</code> for compliance reasons; value is set when contact is created.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'create_source'?: string;
    /**
     * System generated date and time that the resource was created, in ISO-8601 format.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'created_at'?: string;
    /**
     * System generated date and time that the contact was last updated, in ISO-8601 format.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'updated_at'?: string;
    /**
     * For deleted contacts (<code>email_address</code> contains <code>opt_out_source</code> and <code>opt_out_date</code>), shows the date of deletion.
     * @type {string}
     * @memberof GetContactById200Response
     */
    'deleted_at'?: string;
    /**
     * Array of up to 25 <code>custom_field</code> subresources.
     * @type {Array<GetContactById200ResponseCustomFieldsInner>}
     * @memberof GetContactById200Response
     */
    'custom_fields'?: Array<GetContactById200ResponseCustomFieldsInner>;
    /**
     * Array of up to 3 <code>phone_numbers</code> subresources.
     * @type {Array<GetContactById200ResponsePhoneNumbersInner>}
     * @memberof GetContactById200Response
     */
    'phone_numbers'?: Array<GetContactById200ResponsePhoneNumbersInner>;
    /**
     * Array of up to 3 <code>street_addresses</code> subresources.
     * @type {Array<GetContactById200ResponseStreetAddressesInner>}
     * @memberof GetContactById200Response
     */
    'street_addresses'?: Array<GetContactById200ResponseStreetAddressesInner>;
    /**
     * Array of up to 50 <code>list_ids</code> to which the contact is subscribed.
     * @type {Array<string>}
     * @memberof GetContactById200Response
     */
    'list_memberships'?: Array<string>;
    /**
     * Array of tags (<code>tag_id</code>) assigned to the contact, up to a maximum of 50.
     * @type {Array<string>}
     * @memberof GetContactById200Response
     */
    'taggings'?: Array<string>;
    /**
     * An array of notes about the contact listed by most recent note first.
     * @type {Array<GetContactById200ResponseNotesInner>}
     * @memberof GetContactById200Response
     */
    'notes'?: Array<GetContactById200ResponseNotesInner>;
    /**
     * 
     * @type {GetContactById200ResponseSmsChannel}
     * @memberof GetContactById200Response
     */
    'sms_channel'?: GetContactById200ResponseSmsChannel;
}

