/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetContactTrackingReport200ResponseLinksNext } from './get-contact-tracking-report200-response-links-next';

/**
 * HAL property that contains the next link, if applicable.
 * @export
 * @interface GetEmailSendsReport200ResponseLinks
 */
export interface GetEmailSendsReport200ResponseLinks {
    /**
     * 
     * @type {GetContactTrackingReport200ResponseLinksNext}
     * @memberof GetEmailSendsReport200ResponseLinks
     */
    'next': GetContactTrackingReport200ResponseLinksNext;
}

