/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetContactById200ResponsePhoneNumbersInner
 */
export interface GetContactById200ResponsePhoneNumbersInner {
    /**
     * Unique ID for the phone number
     * @type {string}
     * @memberof GetContactById200ResponsePhoneNumbersInner
     */
    'phone_number_id'?: string;
    /**
     * The contact\'s phone number.
     * @type {string}
     * @memberof GetContactById200ResponsePhoneNumbersInner
     */
    'phone_number'?: string;
    /**
     * Identifies the type of phone number; valid values are home, work, mobile, or other.
     * @type {string}
     * @memberof GetContactById200ResponsePhoneNumbersInner
     */
    'kind'?: string;
    /**
     * Date and time that the street address was created, in ISO-8601 format. System generated.
     * @type {string}
     * @memberof GetContactById200ResponsePhoneNumbersInner
     */
    'created_at'?: string;
    /**
     * Date and time that the phone number was last updated, in ISO-8601 format. System generated.
     * @type {string}
     * @memberof GetContactById200ResponsePhoneNumbersInner
     */
    'updated_at'?: string;
    /**
     * Identifies who last updated the phone number; valid values are Contact or Account
     * @type {string}
     * @memberof GetContactById200ResponsePhoneNumbersInner
     */
    'update_source'?: string;
    /**
     * Identifies who added the phone number; valid values are Contact or Account.
     * @type {string}
     * @memberof GetContactById200ResponsePhoneNumbersInner
     */
    'create_source'?: string;
}

