/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetEmailCampaignActivitySchedule200ResponseInner
 */
export interface GetEmailCampaignActivitySchedule200ResponseInner {
    /**
     * The date when Constant Contact will send the email campaign activity to contacts in ISO-8601 format. For example, <code>2022-05-17</code> and <code>2022-05-17T16:37:59.091Z</code> are valid dates.
     * @type {string}
     * @memberof GetEmailCampaignActivitySchedule200ResponseInner
     */
    'scheduled_date'?: string;
}

