/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetBouncesReport200ResponseLinks } from './get-bounces-report200-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetBouncesReport200ResponseTrackingActivitiesInner } from './get-bounces-report200-response-tracking-activities-inner';

/**
 * 
 * @export
 * @interface GetBouncesReport200Response
 */
export interface GetBouncesReport200Response {
    /**
     * The list of email bounce tracking activities associated with a given `campaign_activity_id\'.
     * @type {Array<GetBouncesReport200ResponseTrackingActivitiesInner>}
     * @memberof GetBouncesReport200Response
     */
    'tracking_activities': Array<GetBouncesReport200ResponseTrackingActivitiesInner>;
    /**
     * 
     * @type {GetBouncesReport200ResponseLinks}
     * @memberof GetBouncesReport200Response
     */
    '_links': GetBouncesReport200ResponseLinks;
}

