/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetContactAdds200ResponseTrackingActivitiesInner } from './get-contact-adds200-response-tracking-activities-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetUniqueContactClicks200ResponseLinks } from './get-unique-contact-clicks200-response-links';

/**
 * 
 * @export
 * @interface GetContactAdds200Response
 */
export interface GetContactAdds200Response {
    /**
     * The list of landing page contact adds tracking activities.
     * @type {Array<GetContactAdds200ResponseTrackingActivitiesInner>}
     * @memberof GetContactAdds200Response
     */
    'tracking_activities': Array<GetContactAdds200ResponseTrackingActivitiesInner>;
    /**
     * 
     * @type {GetUniqueContactClicks200ResponseLinks}
     * @memberof GetContactAdds200Response
     */
    '_links': GetUniqueContactClicks200ResponseLinks;
}

