/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetAccountDetails200ResponseCompanyLogo } from './get-account-details200-response-company-logo';
// May contain unused imports in some cases
// @ts-ignore
import { GetAccountDetails200ResponsePhysicalAddress } from './get-account-details200-response-physical-address';

/**
 * 
 * @export
 * @interface GetAccountDetails200Response
 */
export interface GetAccountDetails200Response {
    /**
     * Email addresses that are associated with the Constant Contact account owner.
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'contact_email'?: string;
    /**
     * The account owner\'s contact phone number (up to 25 characters in length).
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'contact_phone'?: string;
    /**
     * The uppercase two-letter <a href=\'https://en.wikipedia.org/wiki/ISO_3166-1\' target=\'_blank\'>ISO 3166-1 code</a> representing the organization\'s country.
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'country_code'?: string;
    /**
     * The readOnly encoded account ID that uniquely identifies the account.
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'encoded_account_id'?: string;
    /**
     * The account owner\'s first name.
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'first_name'?: string;
    /**
     * The account owner\'s last name.
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'last_name'?: string;
    /**
     * The name of the organization that is associated with this account.
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'organization_name'?: string;
    /**
     * The phone number of the organization that is associated with this account.
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'organization_phone'?: string;
    /**
     * The uppercase two letter <a href=\'https://en.wikipedia.org/wiki/ISO_3166-1\' target=\'_blank\'>ISO 3166-1 code</a> for the organization\'s state. This property is required if the <code>country_code</code> is US (United States).
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'state_code'?: string;
    /**
     * The time zone that is automatically set based on the <code>state_code</code> setting; as defined in the IANA time-zone database (see http://www.iana.org/time-zones).
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'time_zone_id'?: string;
    /**
     * The organization\'s website URL.
     * @type {string}
     * @memberof GetAccountDetails200Response
     */
    'website'?: string;
    /**
     * 
     * @type {GetAccountDetails200ResponsePhysicalAddress}
     * @memberof GetAccountDetails200Response
     */
    'physical_address'?: GetAccountDetails200ResponsePhysicalAddress;
    /**
     * 
     * @type {GetAccountDetails200ResponseCompanyLogo}
     * @memberof GetAccountDetails200Response
     */
    'company_logo'?: GetAccountDetails200ResponseCompanyLogo;
}

