/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The physical address of the organization that is sending the email campaign. Constant Contact displays this information to contacts in the email message footer.
 * @export
 * @interface GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
 */
export interface GetEmailCampaignActivity200ResponsePhysicalAddressInFooter {
    /**
     * Line 1 of the organization\'s street address.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'address_line1': string;
    /**
     * Line 2 of the organization\'s street address.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'address_line2'?: string;
    /**
     * Line 3 of the organization\'s street address.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'address_line3'?: string;
    /**
     * An optional address field for the organization. Only <code>format_type</code> 3, 4, and 5 can use this property.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'address_optional'?: string;
    /**
     * The city where the organization sending the email campaign is located.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'city'?: string;
    /**
     * The uppercase two letter <a href=\'https://en.wikipedia.org/wiki/ISO_3166-1\' target=\'_blank\'>ISO 3166-1 code</a> for the organization\'s country.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'country_code': string;
    /**
     * The full name of the country where the organization sending the email is located. Automatically generated using the <code>country_code</code>.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'country_name'?: string;
    /**
     * The name of the organization that is sending the email campaign.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'organization_name': string;
    /**
     * The postal code address (ZIP code) of the organization.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'postal_code'?: string;
    /**
     * The uppercase two letter <a href=\'https://en.wikipedia.org/wiki/ISO_3166-1\' target=\'_blank\'>ISO 3166-1 code</a> for the organization\'s state. This property is required if the <code>country_code</code> is US (United States).
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'state_code'?: string;
    /**
     * The full state name for a <code>state_code</code> that is inside the United States. Automatically generated using the <code>state_code</code>.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'state_name'?: string;
    /**
     * The full state name for a <code>state_code</code> that is outside the United States. This property is not read only.
     * @type {string}
     * @memberof GetEmailCampaignActivity200ResponsePhysicalAddressInFooter
     */
    'state_non_us_name'?: string;
}

