/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetUniqueContactClicks200ResponseLinks } from './get-unique-contact-clicks200-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetUniqueContactOpens200ResponseTrackingActivitiesInner } from './get-unique-contact-opens200-response-tracking-activities-inner';

/**
 * 
 * @export
 * @interface GetUniqueContactOpens200Response
 */
export interface GetUniqueContactOpens200Response {
    /**
     * The list of landing page contact opens tracking activities.
     * @type {Array<GetUniqueContactOpens200ResponseTrackingActivitiesInner>}
     * @memberof GetUniqueContactOpens200Response
     */
    'tracking_activities': Array<GetUniqueContactOpens200ResponseTrackingActivitiesInner>;
    /**
     * 
     * @type {GetUniqueContactClicks200ResponseLinks}
     * @memberof GetUniqueContactOpens200Response
     */
    '_links': GetUniqueContactClicks200ResponseLinks;
}

