/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetContactCounts200Response
 */
export interface GetContactCounts200Response {
    /**
     * Total number of contacts for the account.
     * @type {number}
     * @memberof GetContactCounts200Response
     */
    'total'?: number;
    /**
     * Total number of contacts explicitly confirmed. Consent is obtained when you explicitly ask your potential contacts for permission to send the email (for example, using a sign-up form) and they agree. After you obtain express consent, it is good forever or until the contact opts out.
     * @type {number}
     * @memberof GetContactCounts200Response
     */
    'explicit'?: number;
    /**
     * Total number of contacts implicitly confirmed. Consent is inferred based on actions, such as having an existing business relationship (making a purchase or donation, for example). In order to maintain implied consent to comply with CASL a contact must take a business action with you at least once every two years. Under CAN-Spam there is no need to maintain implied consent, it is assumed until the receiver indicates they no longer wish to receive messages.
     * @type {number}
     * @memberof GetContactCounts200Response
     */
    'implicit'?: number;
    /**
     * Total number of contacts pending confirmation. Consent is requested and pending confirmation from the contact.
     * @type {number}
     * @memberof GetContactCounts200Response
     */
    'pending'?: number;
    /**
     * Total number of unsubscribed contacts. Consent is revoked when a contact has unsubscribed.
     * @type {number}
     * @memberof GetContactCounts200Response
     */
    'unsubscribed'?: number;
    /**
     * Total number of newly subscribed contacts.
     * @type {number}
     * @memberof GetContactCounts200Response
     */
    'new_subscriber'?: number;
}

