/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * HAL property that contains next link if applicable.
 * @export
 * @interface GetAllSegments200ResponseLinksNext
 */
export interface GetAllSegments200ResponseLinksNext {
    /**
     * The next link in the page, or null if there are no additional pages.
     * @type {string}
     * @memberof GetAllSegments200ResponseLinksNext
     */
    'href': string;
}

