/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetEmailStatsReport200ResponseErrorsInner
 */
export interface GetEmailStatsReport200ResponseErrorsInner {
    /**
     * The unique error key.
     * @type {string}
     * @memberof GetEmailStatsReport200ResponseErrorsInner
     */
    'error_key'?: string;
    /**
     * A error description.
     * @type {string}
     * @memberof GetEmailStatsReport200ResponseErrorsInner
     */
    'error_message'?: string;
}

