/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetSmsEngagementHistory200ResponseInnerHistoryDetails } from './get-sms-engagement-history200-response-inner-history-details';

/**
 * Provides a contact\'s SMS engagement history details. The properties returned depend on the type of SMS consent granted by the contact.
 * @export
 * @interface GetSmsEngagementHistory200ResponseInner
 */
export interface GetSmsEngagementHistory200ResponseInner {
    /**
     * The unique contact UUID.
     * @type {string}
     * @memberof GetSmsEngagementHistory200ResponseInner
     */
    'contact_id'?: string;
    /**
     * The unique SMS channel UUID.
     * @type {string}
     * @memberof GetSmsEngagementHistory200ResponseInner
     */
    'sms_channel_id'?: string;
    /**
     * The unique SMS channel history UUID.
     * @type {string}
     * @memberof GetSmsEngagementHistory200ResponseInner
     */
    'sms_channel_history_id'?: string;
    /**
     * The date and time that the history record was created, in ISO-8601 format. System generated.
     * @type {string}
     * @memberof GetSmsEngagementHistory200ResponseInner
     */
    'insert_time'?: string;
    /**
     * 
     * @type {GetSmsEngagementHistory200ResponseInnerHistoryDetails}
     * @memberof GetSmsEngagementHistory200ResponseInner
     */
    'history_details'?: GetSmsEngagementHistory200ResponseInnerHistoryDetails;
}

