/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetEmailOpensReport200ResponseTrackingActivitiesInner
 */
export interface GetEmailOpensReport200ResponseTrackingActivitiesInner {
    /**
     * The ID that uniquely identifies a contact.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'contact_id': string;
    /**
     * The ID that uniquely identifies an email campaign activity.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'campaign_activity_id': string;
    /**
     * The type of tracking activity that is associated with this <code>campaign_activity_id</code> and used for reporting purposes.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'tracking_activity_type': string;
    /**
     * The email address used to send the email campaign activity to a contact.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'email_address': string;
    /**
     * The first name of the contact.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'first_name'?: string;
    /**
     * The last name of the contact.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'last_name'?: string;
    /**
     * The type of device that the contact used to open the email campaign activity.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'device_type'?: string;
    /**
     * The date and time that the contact opened the email campaign activity.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'created_time': string;
    /**
     * If applicable, displays the date that the contact was deleted.
     * @type {string}
     * @memberof GetEmailOpensReport200ResponseTrackingActivitiesInner
     */
    'deleted_at'?: string;
}

