/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Sms channel info for this contact
 * @export
 * @interface GetUniqueContactClicks200ResponseTrackingActivitiesInnerSmsChannel
 */
export interface GetUniqueContactClicks200ResponseTrackingActivitiesInnerSmsChannel {
    /**
     * The ISO country code that is associated with SMS address.
     * @type {string}
     * @memberof GetUniqueContactClicks200ResponseTrackingActivitiesInnerSmsChannel
     */
    'country_code'?: string;
    /**
     * The SMS channel status:   <ul><li><code>N</code>: not_set<li>      <li><code>T</code>: temp_hold<li>      <li><code>P</code>: pending_confirmation<li>      <li><code>I</code>: implicit<li>      <li><code>E</code>: explicit<li>      <li><code>O</code>: unsubscribed<li>      <li><code>D</code>:deprecated<li></ul>
     * @type {string}
     * @memberof GetUniqueContactClicks200ResponseTrackingActivitiesInnerSmsChannel
     */
    'state'?: string;
    /**
     * The formatted SMS number returned if the SMS <code>country_code</code> does not match the contacts <code>country_code</code>. 
     * @type {string}
     * @memberof GetUniqueContactClicks200ResponseTrackingActivitiesInnerSmsChannel
     */
    'formatted_international'?: string;
    /**
     * The formatted SMS number returned if the SMS <code>country_code</code> matches the contacts <code>country_code</code>. 
     * @type {string}
     * @memberof GetUniqueContactClicks200ResponseTrackingActivitiesInnerSmsChannel
     */
    'formatted_national'?: string;
}

