/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetEmailSendsReport200ResponseLinks } from './get-email-sends-report200-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetEmailSendsReport200ResponseTrackingActivitiesInner } from './get-email-sends-report200-response-tracking-activities-inner';

/**
 * 
 * @export
 * @interface GetEmailSendsReport200Response
 */
export interface GetEmailSendsReport200Response {
    /**
     * Lists the contacts to which the email campaign activity (<code>campaign_activity_id</code>) was sent.
     * @type {Array<GetEmailSendsReport200ResponseTrackingActivitiesInner>}
     * @memberof GetEmailSendsReport200Response
     */
    'tracking_activities': Array<GetEmailSendsReport200ResponseTrackingActivitiesInner>;
    /**
     * 
     * @type {GetEmailSendsReport200ResponseLinks}
     * @memberof GetEmailSendsReport200Response
     */
    '_links'?: GetEmailSendsReport200ResponseLinks;
}

