/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetEmailCampaignActivityReport200ResponseResultsInner } from './get-email-campaign-activity-report200-response-results-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GetEmailStatsReport200ResponseErrorsInner } from './get-email-stats-report200-response-errors-inner';

/**
 * 
 * @export
 * @interface GetEmailCampaignActivityReport200Response
 */
export interface GetEmailCampaignActivityReport200Response {
    /**
     * Array of errors indicating any partial failures in the query
     * @type {Array<GetEmailStatsReport200ResponseErrorsInner>}
     * @memberof GetEmailCampaignActivityReport200Response
     */
    'errors'?: Array<GetEmailStatsReport200ResponseErrorsInner>;
    /**
     * An array of results containing statistics for each requested campaign activity
     * @type {Array<GetEmailCampaignActivityReport200ResponseResultsInner>}
     * @memberof GetEmailCampaignActivityReport200Response
     */
    'results'?: Array<GetEmailCampaignActivityReport200ResponseResultsInner>;
}

