/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The base contact tracking activity representing sends, opt-outs and forwards to a friend. The basic information provided includes the campaign activity ID, tracking activity type, and time the tracking activity occurred.
 * @export
 * @interface GetContactTrackingReport200ResponseTrackingActivitiesInner
 */
export interface GetContactTrackingReport200ResponseTrackingActivitiesInner {
    /**
     * The contact ID.
     * @type {string}
     * @memberof GetContactTrackingReport200ResponseTrackingActivitiesInner
     */
    'contact_id': string;
    /**
     * The unique ID of the activity for an e-mail campaign.
     * @type {string}
     * @memberof GetContactTrackingReport200ResponseTrackingActivitiesInner
     */
    'campaign_activity_id': string;
    /**
     * The time the tracking activity occurred
     * @type {string}
     * @memberof GetContactTrackingReport200ResponseTrackingActivitiesInner
     */
    'created_time'?: string;
    /**
     * The types of the tracking activities included in the request. For example, sends, opens, clicks, bounces, opt-outs, or forwards.
     * @type {string}
     * @memberof GetContactTrackingReport200ResponseTrackingActivitiesInner
     */
    'tracking_activity_type'?: string;
    /**
     * The campaign activity name.
     * @type {string}
     * @memberof GetContactTrackingReport200ResponseTrackingActivitiesInner
     */
    'campaign_activity_name'?: string;
}

