/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ListIdList100
 */
export interface ListIdList100 {
    /**
     * The array of contact lists <code>list_id</code> to delete.
     * @type {Array<string>}
     * @memberof ListIdList100
     */
    'list_ids': Array<string>;
}

