/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetUniqueContactClicks200ResponseLinksNext } from './get-unique-contact-clicks200-response-links-next';

/**
 * 
 * @export
 * @interface LpreportingLinks
 */
export interface LpreportingLinks {
    /**
     * 
     * @type {GetUniqueContactClicks200ResponseLinksNext}
     * @memberof LpreportingLinks
     */
    'next': GetUniqueContactClicks200ResponseLinksNext;
}

