/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MyLibraryFileCollectionInnerThumbnail } from './my-library-file-collection-inner-thumbnail';

/**
 * 
 * @export
 * @interface MyLibraryFileCollectionInner
 */
export interface MyLibraryFileCollectionInner {
    /**
     * Identifies the MyLibrary file.
     * @type {number}
     * @memberof MyLibraryFileCollectionInner
     */
    'id'?: number;
    /**
     * The file name.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'name'?: string;
    /**
     * The image height.
     * @type {number}
     * @memberof MyLibraryFileCollectionInner
     */
    'height'?: number;
    /**
     * The image width.
     * @type {number}
     * @memberof MyLibraryFileCollectionInner
     */
    'width'?: number;
    /**
     * The image size.
     * @type {number}
     * @memberof MyLibraryFileCollectionInner
     */
    'size'?: number;
    /**
     * The image URL.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'url'?: string;
    /**
     * The image description.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'description'?: string;
    /**
     * The image folder
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'folder'?: string;
    /**
     * The application that uploaded this image.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'source'?: string;
    /**
     * The image format.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'type'?: string;
    /**
     * The image status.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'status'?: string;
    /**
     * 
     * @type {MyLibraryFileCollectionInnerThumbnail}
     * @memberof MyLibraryFileCollectionInner
     */
    'thumbnail'?: MyLibraryFileCollectionInnerThumbnail;
    /**
     * Boolean indicating if this file is an image.
     * @type {boolean}
     * @memberof MyLibraryFileCollectionInner
     */
    'image'?: boolean;
    /**
     * Identifies a folder in MyLibrary.
     * @type {number}
     * @memberof MyLibraryFileCollectionInner
     */
    'folder_id'?: number;
    /**
     * The external url for the file.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'external_url'?: string;
    /**
     * Identifies the time a user last modified the file.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'modified_date'?: string;
    /**
     * Identifies the time a user originally added the file to MyLibrary.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'added_date'?: string;
    /**
     * External identifier for the file.
     * @type {string}
     * @memberof MyLibraryFileCollectionInner
     */
    'external_file_id'?: string;
}

