/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A note about the contact.
 * @export
 * @interface Note
 */
export interface Note {
    /**
     * The ID that uniquely identifies the note (UUID format).
     * @type {string}
     * @memberof Note
     */
    'note_id'?: string;
    /**
     * The date that the note was created.
     * @type {string}
     * @memberof Note
     */
    'created_at'?: string;
    /**
     * The content for the note.
     * @type {string}
     * @memberof Note
     */
    'content'?: string;
}

