/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PartnerAccountSiteOwnerListInner
 */
export interface PartnerAccountSiteOwnerListInner {
    /**
     * The obfuscated ID used to uniquely identify a client account.
     * @type {string}
     * @memberof PartnerAccountSiteOwnerListInner
     */
    'encoded_account_id'?: string;
    /**
     * The total number of subscriber contacts that are associated with a client account.
     * @type {number}
     * @memberof PartnerAccountSiteOwnerListInner
     */
    'subscriber_count'?: number;
    /**
     * The name of the organization associated with this client account.
     * @type {string}
     * @memberof PartnerAccountSiteOwnerListInner
     */
    'organization_name'?: string;
    /**
     * The user name that identifies a client account.
     * @type {string}
     * @memberof PartnerAccountSiteOwnerListInner
     */
    'site_owner_name'?: string;
    /**
     * The client\'s account billing status. When you first create a client account the `billing status` defaults to `Trial`. Billing status values include: <ul>   <li><code>Trial</code> - A non-paying trial client account (default value).</li>   <li><code>Open</code> - An active and paying client account.</li>   <li><code>Canceled</code> - A canceled client account.</li>   <li><code>Trial End</code> - The trial period has ended for this client account.</li> </ul>
     * @type {string}
     * @memberof PartnerAccountSiteOwnerListInner
     */
    'billing_status'?: string;
    /**
     * The system generated date and time (ISO-8601) showing when the client last logged into their Constant Contact account. If a client has not logged into their account, the value is `null`. This property does not display in the results.
     * @type {string}
     * @memberof PartnerAccountSiteOwnerListInner
     */
    'last_login_date'?: string;
}

