/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PartnerAccountOperationsRequestAccountOperationHeadersInner } from './partner-account-operations-request-account-operation-headers-inner';
// May contain unused imports in some cases
// @ts-ignore
import { PartnerAccountOperationsRequestAccountOperationPathParametersInner } from './partner-account-operations-request-account-operation-path-parameters-inner';
// May contain unused imports in some cases
// @ts-ignore
import { PartnerAccountOperationsRequestAccountOperationQueryParametersInner } from './partner-account-operations-request-account-operation-query-parameters-inner';

/**
 * JSON object that contains the fields Constant Contact uses to construct the HTTP request you are sending on behalf of a managed account.
 * @export
 * @interface PartnerAccountOperationsRequest
 */
export interface PartnerAccountOperationsRequest {
    /**
     * The API method path for the request you are sending on behalf of a managed child account. This value should be a V3 API URL without the https://api.cc.email/v3 base url and with any path parameter names included. For example: <code>/emails/activities/{campaign_activity_id}</code>.
     * @type {string}
     * @memberof PartnerAccountOperationsRequest
     */
    'account_operation_url': string;
    /**
     * The http method for the request you are sending on behalf of a managed child account.
     * @type {string}
     * @memberof PartnerAccountOperationsRequest
     */
    'account_operation_method': string;
    /**
     * The request payload for the request you are sending on behalf of a managed child account. If you provide a JSON payload using this parameter, make sure that the JSON is string escaped.
     * @type {string}
     * @memberof PartnerAccountOperationsRequest
     */
    'account_operation_payload'?: string;
    /**
     * An array containing the query parameters for the request you are sending on behalf of a managed child account.
     * @type {Array<PartnerAccountOperationsRequestAccountOperationQueryParametersInner>}
     * @memberof PartnerAccountOperationsRequest
     */
    'account_operation_query_parameters'?: Array<PartnerAccountOperationsRequestAccountOperationQueryParametersInner>;
    /**
     * An array containing the path parameters for the request you are sending on behalf of a managed child account.
     * @type {Array<PartnerAccountOperationsRequestAccountOperationPathParametersInner>}
     * @memberof PartnerAccountOperationsRequest
     */
    'account_operation_path_parameters'?: Array<PartnerAccountOperationsRequestAccountOperationPathParametersInner>;
    /**
     * An array containing the headers for the request you are sending on behalf of a managed child account.
     * @type {Array<PartnerAccountOperationsRequestAccountOperationHeadersInner>}
     * @memberof PartnerAccountOperationsRequest
     */
    'account_operation_headers'?: Array<PartnerAccountOperationsRequestAccountOperationHeadersInner>;
}

