/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetUniqueContactClicks200ResponseLinks } from './get-unique-contact-clicks200-response-links';
// May contain unused imports in some cases
// @ts-ignore
import { GetUniqueContactClicks200ResponseTrackingActivitiesInner } from './get-unique-contact-clicks200-response-tracking-activities-inner';

/**
 * 
 * @export
 * @interface PContactClickTrackingActivitiesPage
 */
export interface PContactClickTrackingActivitiesPage {
    /**
     * The list of landing page contact click tracking activities.
     * @type {Array<GetUniqueContactClicks200ResponseTrackingActivitiesInner>}
     * @memberof PContactClickTrackingActivitiesPage
     */
    'tracking_activities': Array<GetUniqueContactClicks200ResponseTrackingActivitiesInner>;
    /**
     * 
     * @type {GetUniqueContactClicks200ResponseLinks}
     * @memberof PContactClickTrackingActivitiesPage
     */
    '_links': GetUniqueContactClicks200ResponseLinks;
}

