/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Specifies the type of billing plan and the billing date to use for a client account.
 * @export
 * @interface PlanInfo
 */
export interface PlanInfo {
    /**
     * Use this property to update the client account billing plan to a different billing plan. After changing the <code>plan_type</code> from <code>TRIAL</code> to any other billing plan type, you cannot change it back to <code>TRIAL</code>.   <ul>     <li><code>TRIAL</code>: A non-billable account with an expiration date that allows clients to try Constant Contact product features.</li>      <li><code>GOLD</code>: A billable client account plan.</li>      <li><code>SILVER</code>: A billable client account plan.</li>      <li><code>BRONZE</code>: A billable client account plan.</li>   </ul>
     * @type {string}
     * @memberof PlanInfo
     */
    'plan_type'?: string;
    /**
     * Updates an existing client account billing plan group to a new billing plan group. If you don\'t know the `plan_group_id` to use, contact our API support team.
     * @type {number}
     * @memberof PlanInfo
     */
    'plan_group_id'?: number;
    /**
     * This property is required if a client account is not set up to use single billing. You can choose to enter a specific day of the month or accept the default value, which is the day on which the <code>plan_type</code> value changes from a <code>TRIAL</code> plan to a different <code>plan_type</code>. For trial accounts, the value defaults to null. You can only change the <code>billing_day_of_month</code> when changing the <code>plan_type</code> value from <code>TRIAL</code> to a different <code>plan_type</code>, otherwise the value you enter is ignored.
     * @type {number}
     * @memberof PlanInfo
     */
    'billing_day_of_month'?: number;
}

