/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostTagRequest
 */
export interface PostTagRequest {
    /**
     * Specify a unique name to use to identify the tag. Tag names must be at least one character in length and not more than 255 characters.
     * @type {string}
     * @memberof PostTagRequest
     */
    'name': string;
    /**
     * The source used to identify the contacts to tag.
     * @type {string}
     * @memberof PostTagRequest
     */
    'tag_source'?: string;
}

