/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Provision
 */
export interface Provision {
    /**
     * A valid email address to associate with the client account.
     * @type {string}
     * @memberof Provision
     */
    'contact_email': string;
    /**
     * The contact phone number to associate with the client account.
     * @type {string}
     * @memberof Provision
     */
    'contact_phone'?: string;
    /**
     * The two-letter country code (ISO 3166-1 code) that specifies the country in which the client resides.
     * @type {string}
     * @memberof Provision
     */
    'country_code': string;
    /**
     * The name of organization that identifies the client account.
     * @type {string}
     * @memberof Provision
     */
    'organization_name'?: string;
    /**
     * The organization phone number. To set the organization phone number using the user interface, select <b>My Settings</b> and in the <b>Organization Information</b> section, select <b>Edit Organization Information</b>.
     * @type {string}
     * @memberof Provision
     */
    'organization_phone'?: string;
    /**
     * The two-letter state code that represents the US state (<code>country_code</code> is <code>US</code> ) or Canadian province (<code>country_code</code> is <code>CA</code>) where the client\'s organization is physically located. Leave the <code>state_code</code> blank for non-US states and Canadian provinces.
     * @type {string}
     * @memberof Provision
     */
    'state_code': string;
    /**
     * The offical time zone to use to represent the physical location associated with the client account.
     * @type {string}
     * @memberof Provision
     */
    'time_zone_id'?: string;
    /**
     * The client\'s website URL. Specifying the website URL eliminates the need for clients to provide that information. Requires a valid URL starting with http:// or https://.
     * @type {string}
     * @memberof Provision
     */
    'website'?: string;
    /**
     * A unique login name to associate with the client account. The name must only contain alphanumeric characters and \'-\', \'_\', \'@\',\'.\',\'+\'. 
     * @type {string}
     * @memberof Provision
     */
    'login_name': string;
    /**
     * Required if not using Single Sign On (SSO) or external authenticator. The password to associate with the client account. Passwords must be at least 8 characters and no more than 80 characters in length. Passwords can contain alphabetical letters (A-Z) and (a-z), numbers (0-9), special characters (! @ # $ etc.) and spaces. Passwords should not contain any part of your username and cannot be the same as your last password, or be listed on an industry database; we check for easily guessed or compromised passwords. Your new password is not returned in the response payload for security reasons. If using SSO authentication, use <code>idp_provider</code> and <code>idp_provider_id</code> instead of <code>password</code>.
     * @type {string}
     * @memberof Provision
     */
    'password'?: string;
    /**
     * The client account owner\'s first name.
     * @type {string}
     * @memberof Provision
     */
    'first_name'?: string;
    /**
     * The client account owner\'s last name.
     * @type {string}
     * @memberof Provision
     */
    'last_name'?: string;
    /**
     * The unique client account identifier that partners define and use for billing and reporting purposes.
     * @type {string}
     * @memberof Provision
     */
    'partner_account_id'?: string;
    /**
     * The currency to use when billing the client account. Valid values are: <code>en_US</code> (default, US Dollars) or <code>en_GB</code> (British Pounds).
     * @type {string}
     * @memberof Provision
     */
    'billing_locale'?: string;
    /**
     * By default, if the client account is setup as a managed account <code>managed_site_owner</code> is automatically set to <code>true</code> and attempting to override the setting with <code>false</code> is ignored. This helps to avoid getting an account into an unknown state.
     * @type {boolean}
     * @memberof Provision
     */
    'managed_site_owner'?: boolean;
    /**
     * If a partner account is setup to allow for single billing and the <code>managed_site_owner</code> property is set to <code>true</code>, use this property to enable the single billing feature for the client account. See your account manager for more information.
     * @type {boolean}
     * @memberof Provision
     */
    'enable_single_billing'?: boolean;
    /**
     * When creating accounts for users who have opted-out of any marketing communications, set  the <code> gdpr_opt_out</code>  to <code>true</code>  so that Constant Contact does not send any marketing communications to the account.
     * @type {boolean}
     * @memberof Provision
     */
    'gdpr_opt_out'?: boolean;
    /**
     * The ID used to uniquely identify the client account for the external authenticator. Do not use the <code>password</code> property when using an external authenticator.
     * @type {string}
     * @memberof Provision
     */
    'external_id'?: string;
    /**
     * The name of the provider who externally authenticates this customer. For example, PayPal or Yahoo. Do not use the <code>password</code> property when using an external authenticator.
     * @type {string}
     * @memberof Provision
     */
    'external_provider'?: string;
}

