/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SegmentMaster
 */
export interface SegmentMaster {
    /**
     * The segment\'s unique descriptive name.
     * @type {string}
     * @memberof SegmentMaster
     */
    'name'?: string;
    /**
     * The system generated number that uniquely identifies the segment.
     * @type {number}
     * @memberof SegmentMaster
     */
    'segment_id'?: number;
    /**
     * The system generated date and time that the segment was created (ISO-8601 format).
     * @type {string}
     * @memberof SegmentMaster
     */
    'created_at'?: string;
    /**
     * The system generated date and time that the segment\'s <code>name</code> or <code>segment_criteria</code> was last updated (ISO-8601 format).
     * @type {string}
     * @memberof SegmentMaster
     */
    'edited_at'?: string;
}

