/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Provides SMS consent details.
 * @export
 * @interface SmsChannelConsentDetails
 */
export interface SmsChannelConsentDetails {
    /**
     * Identifies the current permission status for the SMS channel.
     * @type {string}
     * @memberof SmsChannelConsentDetails
     */
    'sms_consent_permission'?: string;
    /**
     * 
     * @type {string}
     * @memberof SmsChannelConsentDetails
     */
    'consent_type'?: string;
    /**
     * Date and time, in ISO-8601 format, that the contact subscribed/opted-in to receiving SMS from the account. Displays only if the contact subscribes/opts-in. System generated.
     * @type {string}
     * @memberof SmsChannelConsentDetails
     */
    'opt_in_date'?: string;
    /**
     * Date and time, in ISO-8601 format, that the contact unsubscribed/opted-out of receiving SMS from the account. Displays only if the contact unsubscribed/opted-out. System generated.
     * @type {string}
     * @memberof SmsChannelConsentDetails
     */
    'opt_out_date'?: string;
    /**
     * The numeric used to set how often to send SMS advertisements during a specified time interval (<code>advertised_interval</code>). For example, if the <code>advertised_frequency</code> is set to <code>2</code> and the  <code>advertised_interval</code> is set to <code>monthly</code>, the contact can receive up to two advertisements per month.
     * @type {string}
     * @memberof SmsChannelConsentDetails
     */
    'advertised_frequency'?: string;
    /**
     * Identifies the unit of time used by Constant Contact to send SMS advertisements as a string enum. For example, if the <code>advertised_frequency</code> is set to <code>2</code> and the <code>advertised_interval</code> is set to <code>monthly</code>, the contact can receive up to two advertisements per month.
     * @type {string}
     * @memberof SmsChannelConsentDetails
     */
    'advertised_interval'?: string;
    /**
     * Date and time that the SMS stats were created, in ISO-8601 format. System generated.
     * @type {string}
     * @memberof SmsChannelConsentDetails
     */
    'created_at'?: string;
    /**
     * Date and time that the SMS stats were updated, in ISO-8601 format. System generated.
     * @type {string}
     * @memberof SmsChannelConsentDetails
     */
    'updated_at'?: string;
}

