/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.116
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetAllTags200ResponseLinksNextNext } from './get-all-tags200-response-links-next-next';

/**
 * 
 * @export
 * @interface TagsLinks
 */
export interface TagsLinks {
    /**
     * 
     * @type {string}
     * @memberof TagsLinks
     */
    'href'?: string;
    /**
     * 
     * @type {GetAllTags200ResponseLinksNextNext}
     * @memberof TagsLinks
     */
    'next'?: GetAllTags200ResponseLinksNextNext;
}

