/* tslint:disable */
/* eslint-disable */
/**
 * Constant Contact API v3
 * Swagger build version 3.0.2475
 *
 * The version of the OpenAPI document: 1.0.85
 * Contact: webservices@constantcontact.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateContactRequestStreetAddressesInner
 */
export interface UpdateContactRequestStreetAddressesInner {
    /**
     * Describes the type of address; valid values are home, work, or other.
     * @type {string}
     * @memberof UpdateContactRequestStreetAddressesInner
     */
    'kind': string;
    /**
     * Number and street of the address.
     * @type {string}
     * @memberof UpdateContactRequestStreetAddressesInner
     */
    'street'?: string;
    /**
     * The name of the city where the contact lives.
     * @type {string}
     * @memberof UpdateContactRequestStreetAddressesInner
     */
    'city'?: string;
    /**
     * The name of the state or province where the contact lives.
     * @type {string}
     * @memberof UpdateContactRequestStreetAddressesInner
     */
    'state'?: string;
    /**
     * The zip or postal code of the contact.
     * @type {string}
     * @memberof UpdateContactRequestStreetAddressesInner
     */
    'postal_code'?: string;
    /**
     * The name of the country where the contact lives.
     * @type {string}
     * @memberof UpdateContactRequestStreetAddressesInner
     */
    'country'?: string;
}

